Handle worker thread errors more gracefully (#583)
We were getting some real sketchy output:

```
(node:212) UnhandledPromiseRejectionWarning: Error: EBADF: bad file descriptor, close
(Use `node --trace-warnings ...` to show where the warning was created)
(node:212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Worker exited without posting a message
```